// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_account_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_account_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_account_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_account_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_account_2eproto;
class CAccount;
class CAccountDefaultTypeInternal;
extern CAccountDefaultTypeInternal _CAccount_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::CAccount* Arena::CreateMaybeMessage<::CAccount>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class CAccount PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CAccount) */ {
 public:
  inline CAccount() : CAccount(nullptr) {};
  virtual ~CAccount();

  CAccount(const CAccount& from);
  CAccount(CAccount&& from) noexcept
    : CAccount() {
    *this = ::std::move(from);
  }

  inline CAccount& operator=(const CAccount& from) {
    CopyFrom(from);
    return *this;
  }
  inline CAccount& operator=(CAccount&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CAccount& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CAccount* internal_default_instance() {
    return reinterpret_cast<const CAccount*>(
               &_CAccount_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CAccount& a, CAccount& b) {
    a.Swap(&b);
  }
  inline void Swap(CAccount* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CAccount* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CAccount* New() const final {
    return CreateMaybeMessage<CAccount>(nullptr);
  }

  CAccount* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CAccount>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CAccount& from);
  void MergeFrom(const CAccount& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CAccount* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CAccount";
  }
  protected:
  explicit CAccount(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_account_2eproto);
    return ::descriptor_table_account_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStrUserNameFieldNumber = 1,
    kStrEmailFieldNumber = 2,
  };
  // required string strUserName = 1;
  bool has_strusername() const;
  private:
  bool _internal_has_strusername() const;
  public:
  void clear_strusername();
  const std::string& strusername() const;
  void set_strusername(const std::string& value);
  void set_strusername(std::string&& value);
  void set_strusername(const char* value);
  void set_strusername(const char* value, size_t size);
  std::string* mutable_strusername();
  std::string* release_strusername();
  void set_allocated_strusername(std::string* strusername);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_strusername();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_strusername(
      std::string* strusername);
  private:
  const std::string& _internal_strusername() const;
  void _internal_set_strusername(const std::string& value);
  std::string* _internal_mutable_strusername();
  public:

  // required string strEmail = 2;
  bool has_stremail() const;
  private:
  bool _internal_has_stremail() const;
  public:
  void clear_stremail();
  const std::string& stremail() const;
  void set_stremail(const std::string& value);
  void set_stremail(std::string&& value);
  void set_stremail(const char* value);
  void set_stremail(const char* value, size_t size);
  std::string* mutable_stremail();
  std::string* release_stremail();
  void set_allocated_stremail(std::string* stremail);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_stremail();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_stremail(
      std::string* stremail);
  private:
  const std::string& _internal_stremail() const;
  void _internal_set_stremail(const std::string& value);
  std::string* _internal_mutable_stremail();
  public:

  // @@protoc_insertion_point(class_scope:CAccount)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr strusername_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr stremail_;
  friend struct ::TableStruct_account_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CAccount

// required string strUserName = 1;
inline bool CAccount::_internal_has_strusername() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool CAccount::has_strusername() const {
  return _internal_has_strusername();
}
inline void CAccount::clear_strusername() {
  strusername_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& CAccount::strusername() const {
  // @@protoc_insertion_point(field_get:CAccount.strUserName)
  return _internal_strusername();
}
inline void CAccount::set_strusername(const std::string& value) {
  _internal_set_strusername(value);
  // @@protoc_insertion_point(field_set:CAccount.strUserName)
}
inline std::string* CAccount::mutable_strusername() {
  // @@protoc_insertion_point(field_mutable:CAccount.strUserName)
  return _internal_mutable_strusername();
}
inline const std::string& CAccount::_internal_strusername() const {
  return strusername_.Get();
}
inline void CAccount::_internal_set_strusername(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  strusername_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void CAccount::set_strusername(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  strusername_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:CAccount.strUserName)
}
inline void CAccount::set_strusername(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  strusername_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:CAccount.strUserName)
}
inline void CAccount::set_strusername(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  strusername_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:CAccount.strUserName)
}
inline std::string* CAccount::_internal_mutable_strusername() {
  _has_bits_[0] |= 0x00000001u;
  return strusername_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* CAccount::release_strusername() {
  // @@protoc_insertion_point(field_release:CAccount.strUserName)
  if (!_internal_has_strusername()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return strusername_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CAccount::set_allocated_strusername(std::string* strusername) {
  if (strusername != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  strusername_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), strusername,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:CAccount.strUserName)
}
inline std::string* CAccount::unsafe_arena_release_strusername() {
  // @@protoc_insertion_point(field_unsafe_arena_release:CAccount.strUserName)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000001u;
  return strusername_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void CAccount::unsafe_arena_set_allocated_strusername(
    std::string* strusername) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (strusername != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  strusername_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      strusername, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:CAccount.strUserName)
}

// required string strEmail = 2;
inline bool CAccount::_internal_has_stremail() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool CAccount::has_stremail() const {
  return _internal_has_stremail();
}
inline void CAccount::clear_stremail() {
  stremail_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& CAccount::stremail() const {
  // @@protoc_insertion_point(field_get:CAccount.strEmail)
  return _internal_stremail();
}
inline void CAccount::set_stremail(const std::string& value) {
  _internal_set_stremail(value);
  // @@protoc_insertion_point(field_set:CAccount.strEmail)
}
inline std::string* CAccount::mutable_stremail() {
  // @@protoc_insertion_point(field_mutable:CAccount.strEmail)
  return _internal_mutable_stremail();
}
inline const std::string& CAccount::_internal_stremail() const {
  return stremail_.Get();
}
inline void CAccount::_internal_set_stremail(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  stremail_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void CAccount::set_stremail(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  stremail_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:CAccount.strEmail)
}
inline void CAccount::set_stremail(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  stremail_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:CAccount.strEmail)
}
inline void CAccount::set_stremail(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000002u;
  stremail_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:CAccount.strEmail)
}
inline std::string* CAccount::_internal_mutable_stremail() {
  _has_bits_[0] |= 0x00000002u;
  return stremail_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* CAccount::release_stremail() {
  // @@protoc_insertion_point(field_release:CAccount.strEmail)
  if (!_internal_has_stremail()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return stremail_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CAccount::set_allocated_stremail(std::string* stremail) {
  if (stremail != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  stremail_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), stremail,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:CAccount.strEmail)
}
inline std::string* CAccount::unsafe_arena_release_stremail() {
  // @@protoc_insertion_point(field_unsafe_arena_release:CAccount.strEmail)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000002u;
  return stremail_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void CAccount::unsafe_arena_set_allocated_stremail(
    std::string* stremail) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (stremail != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  stremail_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      stremail, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:CAccount.strEmail)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_account_2eproto
